### ISSUE TITLE
Exception thrown when using a "selector" with "copy-messages"

### ISSUE THREAD

**Issue by chiriaev** [antonwierenga/activemq-cli#14]
Guys, Hi. Great application. Thanks. I need your help. Trying to copy messages with a selector. The below is thrown whatever I put in as value of the "--selector" flag. Trying "priority = '4'", with and without single quotes. The "priority" field is part of my "header" under the "jms-message" XML element. The copy works well without it.

My ActiveMQ version is "5.9.1". I am also using your latest "0.6.0" release.

Thanks in advance.

Regards, Andrei
...
java.lang.NullPointerException
        at org.apache.activemq.filter.MessageEvaluationContext.clearMessageCache(MessageEvaluationContext.java:89)
        at org.apache.activemq.filter.MessageEvaluationContext.setMessageReference(MessageEvaluationContext.java:66)
        at org.apache.activemq.broker.region.Queue$7.evaluate(Queue.java:1750)
        at org.apache.activemq.broker.region.Queue.copyMatchingMessages(Queue.java:1451)
        at org.apache.activemq.broker.region.Queue.copyMatchingMessagesTo(Queue.java:1423)
        at org.apache.activemq.broker.region.Queue.copyMatchingMessagesTo(Queue.java:1412)
        at org.apache.activemq.broker.jmx.QueueView.copyMatchingMessagesTo(QueueView.java:80)
...

**Comment by antonwierenga** [comment]
In the --selector you have to use the corresponding [JMS Header Field](https://docs.oracle.com/cd/E19798-01/821-1841/bncet/index.html) or Property Name. Can you try --selector "JMSPriority = 4"?

![Screenshot 2019-05-10 at 21 14 23](https://user-images.githubusercontent.com/14827290/57551151-a4315400-7368-11e9-8456-e3bff23d3d1a.jpg)

**Comment by chiriaev** [comment]
Hi, @antonwierenga. Thanks for the prompt feedback. Same results, as per the below. Regards, Andrei

P.S.: it works when the selector is NULL; I tried with ActiveMQ 5.9.1 (all-in) JAR; same stuff.
...
Welcome to ActiveMQ CLI v0.6.0
activemq-cli>connect --broker local
Connected to broker 'local'
local>copy-messages --from DLQ.objectevent --selector "JMSPriority = 4" --to test-copy
Command failed java.lang.NullPointerException
java.lang.NullPointerException
        at org.apache.activemq.filter.MessageEvaluationContext.clearMessageCache(MessageEvaluationContext.java:89)
        at org.apache.activemq.filter.MessageEvaluationContext.setMessageReference(MessageEvaluationContext.java:66)
        at org.apache.activemq.broker.region.Queue$7.evaluate(Queue.java:1750)
        at org.apache.activemq.broker.region.Queue.copyMatchingMessages(Queue.java:1451)
        at org.apache.activemq.broker.region.Queue.copyMatchingMessagesTo(Queue.java:1423)
        at org.apache.activemq.broker.region.Queue.copyMatchingMessagesTo(Queue.java:1412)
        at org.apache.activemq.broker.jmx.QueueView.copyMatchingMessagesTo(QueueView.java:80)
        at sun.reflect.GeneratedMethodAccessor5910.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:75)
        at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:279)
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
        at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
        at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
        at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
        at javax.management.StandardMBean.invoke(StandardMBean.java:405)
        at org.apache.activemq.broker.jmx.AnnotatedMBean.invoke(AnnotatedMBean.java:198)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
        at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1487)
        at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:97)
        at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1328)
        at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1420)
        at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:848)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:322)
        at sun.rmi.transport.Transport$1.run(Transport.java:177)
        at sun.rmi.transport.Transport$1.run(Transport.java:174)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:173)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:553)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:808)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:667)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:724)
local>copy-messages --from DLQ.objectevent --selector "__NULL__" --to test-copy
Copied 48 messages from 'DLQ.objectevent' to 'test-copy'
...

**Comment by antonwierenga** [comment]
I also tested this wil the activemq-all-5.9.1.jar and the copy-messages command with --selector "JMSPriority = 4" works fine for me.

This is what I did:
- Replace org.apache.activemq.activemq-all-5.13.1.jar with activemq-all-5.9.1.jar in activemq-cli/lib
- In the startup script activemq-cli/bin/activemq-cli (or activemq-cli.bat for Windows) replace org.apache.activemq.activemq-all-5.13.1.jar with activemq-all-5.9.1.jar

![Screenshot 2019-05-14 at 22 25 21](https://user-images.githubusercontent.com/14827290/57729829-664d6c00-7697-11e9-9074-8980f6cfec02.jpg)

**Comment by chiriaev** [comment]
Hi, @antonwierenga. Thanks for this. I already tried and unfortunately it doesn't change a thing. Still throwing the exception when using the selector. Could it be related to the message structure, as per the below? Could you please give it a try? 

Thanks in advance.

Regards, Andrei
```
<jms-messages>
  <jms-message>
    <header>
      <message-id>ID:c436qwj-58578-1550920455434-1:1:11773195:1:1</message-id>
      <delivery-mode>2</delivery-mode>
      <destination>queue://DLQ.ftpevent</destination>
      <expiration>0</expiration>
      <priority>4</priority>
      <redelivered>false</redelivered>
      <timestamp>2019-03-27T12:54:49</timestamp>
    </header>
    <properties>
      <property>
        <name>esb_parameters_sourceToken</name>
        <value>LAST_UPDATE</value>
      </property>
      <property>
        <name>esb_parameters_ftpformatid</name>
        <value>16</value>
      </property>
      <property>
        <name>esb_parameters_rundatetime</name>
        <value>1553558400000</value>
      </property>
      <property>
        <name>esb_timeStamp</name>
        <value>2019-03-27T12:54:49</value>
      </property>
      <property>
        <name>esb_parameters_objectid</name>
        <value>5025888</value>
      </property>
      <property>
        <name>esb_msgId</name>
        <value>803189e4ff5a444d9fdf2fb6b087f6d7</value>
      </property>
      <property>
        <name>esb_parameters_lastupdate</name>
        <value>1553642801000</value>
      </property>
    </properties>
  </jms-message>
</jms-messages>  
```

**Comment by antonwierenga** [comment]
I tried your message and I still cannot reproduce the error:

![Screenshot 2019-05-16 at 20 41 24](https://user-images.githubusercontent.com/14827290/57878749-041d7400-781b-11e9-983e-0ffe89f65d8f.jpg)

Are you running into this error when you execute above commands (activemq-cli configured with activemq-all-5.9.1.jar and ~/Desktop/issue_14.xml containing your XML)?

**Comment by chiriaev** [comment]
Hi, @antonwierenga. Thanks a lot for your help. Unfortunately, I am still getting the same exception back.

The "classpath" seems accurate after using "-debug" option. Could the Java version be the troublemaker?

Regards, Andrei
```
# which java
/usr/bin/java

# java -version
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (build 1.8.0_201-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)

# ./activemq-cli
   ___      __  _          __  _______     _______   ____
  / _ |____/ /_(_)  _____ /  |/  / __ \   / ___/ /  /  _/
 / __ / __/ __/ / |/ / -_) /|_/ / /_/ /  / /__/ /___/ /
/_/ |_\__/\__/_/|___/\__/_/  /_/\___\_\  \___/____/___/
                                                        
Welcome to ActiveMQ CLI v0.6.0
activemq-cli>connect --broker local
Connected to broker 'local'
local>info
  Broker ID                           Broker Name  Broker Version  Memory Limit used  Store Limit used  Uptime           Queues  Topics  Messages  Consumers
  ----------------------------------  -----------  --------------  -----------------  ----------------  ---------------  ------  ------  --------  ---------
  ID:c436qwj-40955-1557619742913-0:1  localhost    5.9.1           5%                 23%               4 days 18 hours  20      25      314518    80

local>send-message --file /local/spool/test.xml --queue test-queue
Messages sent to queue 'test-queue': 1

local>list-messages --queue test-queue
<jms-message>
  <header>
    <message-id>ID:c436qwj-40955-1557619742913-3:1:1:1:1</message-id>
    <delivery-mode>2</delivery-mode>
    <destination>queue://test-queue</destination>
    <expiration>0</expiration>
    <priority>4</priority>
    <redelivered>false</redelivered>
    <timestamp>2019-05-16T18:55:10</timestamp>
  </header>
  <properties>
    <property>
      <name>esb_parameters_sourceToken</name>
      <value>LAST_UPDATE</value>
    </property>
    <property>
      <name>esb_parameters_ftpformatid</name>
      <value>16</value>
    </property>
    <property>
      <name>esb_parameters_rundatetime</name>
      <value>1553558400000</value>
    </property>
    <property>
      <name>esb_timeStamp</name>
      <value>2019-03-27T12:54:49</value>
    </property>
    <property>
      <name>esb_parameters_objectid</name>
      <value>5025888</value>
    </property>
    <property>
      <name>esb_msgId</name>
      <value>803189e4ff5a444d9fdf2fb6b087f6d7</value>
    </property>
    <property>
      <name>esb_parameters_lastupdate</name>
      <value>1553642801000</value>
    </property>
  </properties>
</jms-message>

Messages listed: 1

local>copy-messages --from test-queue --to test-queue2 --selector "JMSPriority = 4"
Command failed java.lang.NullPointerException
java.lang.NullPointerException
        at org.apache.activemq.filter.MessageEvaluationContext.clearMessageCache(MessageEvaluationContext.java:89)
        at org.apache.activemq.filter.MessageEvaluationContext.setMessageReference(MessageEvaluationContext.java:66)
        at org.apache.activemq.broker.region.Queue$7.evaluate(Queue.java:1750)
        at org.apache.activemq.broker.region.Queue.copyMatchingMessages(Queue.java:1451)
        at org.apache.activemq.broker.region.Queue.copyMatchingMessagesTo(Queue.java:1423)
        at org.apache.activemq.broker.region.Queue.copyMatchingMessagesTo(Queue.java:1412)
        at org.apache.activemq.broker.jmx.QueueView.copyMatchingMessagesTo(QueueView.java:80)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
        at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
        at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
        at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
        at javax.management.StandardMBean.invoke(StandardMBean.java:405)
        at org.apache.activemq.broker.jmx.AnnotatedMBean.invoke(AnnotatedMBean.java:198)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
        at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
        at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
        at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
        at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
        at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by antonwierenga** [comment]
My tests were initially executed using Oracje JDK. I switched to OpenJDK and still no luck in reproducing the error.

#java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)"

**Comment by chiriaev** [comment]
Hi, @antonwierenga. It works when going through the embedded broker. I checked the ActiveMQ ".jar" files are identical between the real broker and your tool, that's after patching it to use my own version from your feedback.

Is there anything else I could attempt? Increasing log verbosity, for example or attaching a debugger?

Regards, Andrei

**Comment by antonwierenga** [comment]
I don't think increasing log verbosity will help. It's pretty clear where the NullPointerException occurs.
Maybe you can try the ActiveMQ forum or -if you know how to code- write reproduce case and file a (ActiveMQ) bug report.
