### ISSUE TITLE
Error when trying to dump a large deadletter queue

### ISSUE THREAD

**Issue by fredex42** [antonwierenga/activemq-cli#4]
Hi there, I am trying to use activemq-cli to dump out the contents of a very large (>90k messages) deadletter queue to send to the software vendor for advice. Unfortunately, after 3,944 messages have been processed the export-messages command fails with the following stack trace:

```
Command failed java.lang.NullPointerException
java.lang.NullPointerException
        at activemq.cli.util.Implicits$MessageImprovements.toXML(Implicits.scala
:83)
        at activemq.cli.command.MessageCommands$$anonfun$2.apply(MessageCommands
.scala:177)
        at activemq.cli.command.MessageCommands$$anonfun$2.apply(MessageCommands
.scala:176)
        at activemq.cli.command.Commands$$anonfun$withEveryMirrorQueueMessage$1$
$anonfun$apply$4$$anonfun$apply$1.apply$mcVI$sp(Commands.scala:191)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
        at activemq.cli.command.Commands$$anonfun$withEveryMirrorQueueMessage$1$
$anonfun$apply$4.apply(Commands.scala:187)
        at activemq.cli.command.Commands$$anonfun$withEveryMirrorQueueMessage$1$
$anonfun$apply$4.apply(Commands.scala:183)
        at activemq.cli.command.Commands.withSession(Commands.scala:136)
        at activemq.cli.command.Commands$$anonfun$withEveryMirrorQueueMessage$1.
apply(Commands.scala:183)
        at activemq.cli.command.Commands$$anonfun$withEveryMirrorQueueMessage$1.
apply(Commands.scala:177)
        at activemq.cli.command.Commands.withBroker(Commands.scala:163)
        at activemq.cli.command.Commands.withEveryMirrorQueueMessage(Commands.scala:177)
        at activemq.cli.command.MessageCommands.exportMessages(MessageCommands.scala:175)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:196)
        at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:64)
        at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:48)
        at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:127)
        at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
        at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
        at java.lang.Thread.run(Thread.java:724)
``` 

Please can you advise on how I can work around this problem?

thanks

**Comment by fredex42** [comment]
I coded a workaround and submitted a PR - this got me result that I needed

**Comment by antonwierenga** [comment]
Thanks for reporting.
